#!/bin/bash

while true
do
#  if [[ $(ip a | grep -A 0 tun | awk '{print $2}' | tail -n1) ]];
#  then
#	VPN="[VPN] |";
#  else
#	VPN="";
#  fi
  VOL=`pamixer --get-volume`
  TIME=`date '+%H:%M:%S'`
  BAT0=`cat /sys/class/power_supply/BAT0/capacity`
  BAT1=`cat /sys/class/power_supply/BAT1/capacity`
#  IP=$(for i in `ip r`; do echo $i; done | grep -A 1 src | tail -n1)
  BAT=$(( ( $BAT0 + $BAT1 ) / 2))
  xsetroot -name " volume: $VOL% | bat: $BAT% | time: $TIME"
  sleep 5
done

