#!/bin/bash

while true
do
  PKGS=`paru -Qu | wc -l`
  MUTED=`pamixer --get-mute`

  UPDATES=`test $PKGS -gt 0 && echo "Updates: $PKGS" || echo ""`
  VOL=`test $MUTED = true && echo "volume: MUTED" || echo "volume: $(pamixer --get-volume)%"`
  TIME="time: `date '+%H:%M:%S'`"
  xsetroot -name "$UPDATES | $VOL | $TIME"
  sleep 1
done

