#!/bin/bash

while true
do
  VOL=`pamixer --get-volume || :`
  TIME=`date '+%H:%M:%S'`
  BAT0=`cat /sys/class/power_supply/BAT0/capacity || :`
  BAT1=`cat /sys/class/power_supply/BAT1/capacity || :`
  BAT=`$(( ( $BAT0 + $BAT1 ) / 2)) || :`
  xsetroot -name " volume: $VOL% | bat: $BAT% | time: $TIME"
  sleep 5
done

